apiVersion: v1
metadata:
  name: proxy-svc
  namespace: default
  labels:
    app: proxy-svc
spec:
  ports:
    - name: 8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mitmproxy
  type: ClusterIP
kind: Service
