apiVersion: v1
kind: ServiceAccount
metadata:
  name: mitmproxy
  namespace: default
  labels:
    app: mitmproxy
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mitmproxy
  namespace: default
  labels:
    app: mitmproxy
subjects:
- kind: ServiceAccount
  name: mitmproxy
  namespace: default
roleRef:
  kind: Role
  name: mitmproxy
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mitmproxy
  namespace: default
  labels:
    app: mitmproxy
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  resourceNames:
  - mitmproxy-config
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
  - mitmproxy-certs
  verbs: ["get", "list"]
