apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: mitmproxy-certs
  labels:
    app: mitmproxy
data:
  mitmproxy-ca-cert.cer: |-
    {{ .Files.Get "certs/mitmproxy-ca-cert.cer" | b64enc }}
  mitmproxy-ca-cert.p12: |-
    {{ .Files.Get "certs/mitmproxy-ca-cert.p12" | b64enc }}
  mitmproxy-ca-cert.pem: |-
    {{ .Files.Get "certs/mitmproxy-ca-cert.pem" | b64enc }}
  mitmproxy-ca.pem: |-
    {{ .Files.Get "certs/mitmproxy-ca.pem" | b64enc }}
  mitmproxy-dhparam.pem: |-
    {{ .Files.Get "certs/mitmproxy-dhparam.pem" | b64enc }}
