apiVersion: v1
kind: ConfigMap
metadata:
  name: mitmproxy-root-certs
  labels:
    app: mitmproxy
data:
  root-certs.crt: |-
    {{ range .Files.Lines "config/root-certs.crt" }}
    {{ . }}{{ end }}{{ range .Files.Lines "certs/mitmproxy-ca-cert.cer" }}
    {{ . }}{{ end }}
